#include <stdio.h>
#include "erpc_matrix_multiply.h"  // auto-generated by erpcgen
#include "erpc_client_setup.h"     // from erpc source


void print_matrix(Matrix mat, int32_t rows, int32_t cols)
{
    int32_t row, col;
    
    for (row = 0; row < rows; row++)
    {
        for(col = 0; col < cols; col++)
        {
             printf("%d     ", mat[row][col]);
        }
        
        printf("\n");
    }
    
    printf("\n");
}

int main()
{
    printf("Initializing... ");
    
    /* Matrices definitions */
    Matrix matrix1, matrix2, result_matrix = {{0}};

    /* Init eRPC client environment */
    /* TCP transport layer initialization */
    erpc_transport_t transport = erpc_transport_tcp_init("127.0.0.1", 5407, false);

    /* MessageBufferFactory initialization */
    erpc_mbf_t message_buffer_factory = erpc_mbf_dynamic_init();

    /* eRPC client side initialization */
    erpc_client_init(transport, message_buffer_factory);
    
    printf("Done.\n");

    /* other code like init matrix1 and matrix2 values */
    for (int i = 0; i < matrix_size; i++) 
    {
        for (int j = 0; j < matrix_size; j++)
        {
            matrix1[i][j] = j + 1;
            matrix2[i][j] = (j + 1) * 2;
        }
    } 
    
    print_matrix(matrix1, matrix_size, matrix_size);
    print_matrix(matrix2, matrix_size, matrix_size);

    /* call eRPC functions */
    erpcMatrixMultiply(matrix1, matrix2, result_matrix);

    /* other code like print result matrix */
    printf("Received result...\n");
    print_matrix(result_matrix, matrix_size, matrix_size);

    return 0;
}

